//! LILA engine build profile — GENERATED by scripts/build_engine.sh.
//! (The committed file holds the v1 defaults; the build script rewrites it
//! per profile, builds, then restores defaults.)
//!
//! Every value here is comptime: the optimizer specializes pool sizes and
//! the whole memory map for this profile. There is ZERO runtime cost to
//! configurability — the shipped wasm is exactly as tight as a hand-fixed
//! build (this is the "generated config.h" technique production C/C++
//! engines use, applied to a wasm VM).
//!
//! Constraint: MEM_MB * 1MB must cover the derived memory map
//! (core.zig asserts this at compile time).

pub const PROFILE_NAME: []const u8 = "default";

/// entity types the build supports (v7 knob; default 16 = v1 layout)
pub const MAX_TYPES: u32 = 16;
/// total flat engine memory in MB (the "2MB WASM" — now a knob)
pub const MEM_MB: u32 = 2;
/// entity slots per type (was 512)
pub const MAX_ENT: u32 = 512;
/// render vertex budget per frame (was 6000)
pub const MAX_VERTS: u32 = 6000;
/// decoded instruction capacity (was 8192)
pub const MAX_INSTR: u32 = 8192;
/// sprite slots (was 64)
pub const MAX_SPRITES: u32 = 64;
/// text atoms (was 32)
pub const MAX_TEXTS: u32 = 32;
/// anim curves (was 32)
pub const MAX_ANIMS: u32 = 32;
/// functions (was 128)
pub const MAX_FNS: u32 = 128;
/// constant pool slots (was 1024)
pub const MAX_POOL: u32 = 1024;
/// music tracks (was 8)
pub const MAX_TRACKS: u32 = 8;
/// sfx programs (was 32)
pub const MAX_SFX: u32 = 32;
/// v12 PROFILE KNOB: 3D rasterizer depth variant. false = painter's
/// algorithm (v11 default, zero extra memory); true = per-pixel Z-buffer
/// (correct triangle-triangle occlusion, +512KB depth buffer). The runner
/// can still override per-run with --zbuffer / --no-zbuffer.
pub const ZBUFFER3D: bool = false;
/// v15 PROFILE KNOB: gamma-correct blending. false = blend directly in
/// 8-bit sRGB (legacy — pixel-identical to v14); true = convert RGB
/// sRGB->linear, blend, convert back (LUT-based, see raster.zig; alpha is
/// coverage and is never converted). Affects the CPU rasterizer only:
/// wasm hosts rasterize on the GPU and should match this in their
/// uber-shader. The runner can override per-run with --gamma / --no-gamma.
pub const GAMMA_BLEND: bool = false;
