//! GENERATED by the lilac v8 optimizer (opt::soa) — comptime manifest.
//! Do not edit: regenerate with `lilac build --emit-zig-opt runtime/src/lila_opt.zig`.
//!
//! This file IS the cross-optimization contract between the compiler and
//! the Zig engine build: the .libyte schema carries the same layout, and
//! these comptime tables + asserts re-prove it inside the Zig compiler
//! (`zig test lila_opt.zig`). Zero runtime cost — everything here is
//! resolved at comptime; nothing ships in the wasm.

const std = @import("std");

pub const FieldLayout = struct {
    name: []const u8,
    bits: u8,
    off_bits: u16,
    cold: bool,
};

pub const EntLayout = struct {
    name: []const u8,
    row_bytes: u16,
    cold_bytes: u16,
    hot_bytes: u16, // register-window segment (<= 16B when possible)
    fields: []const FieldLayout,
};

pub const OPTIMIZE: bool = true;

pub const ENTITIES = [_]EntLayout{
    .{ .name = "Drone", .row_bytes = 18, .cold_bytes = 1, .hot_bytes = 16, .fields = &[_]FieldLayout{
        .{ .name = "x", .bits = 32, .off_bits = 0, .cold = false },
        .{ .name = "y", .bits = 32, .off_bits = 32, .cold = false },
        .{ .name = "vx", .bits = 32, .off_bits = 64, .cold = false },
        .{ .name = "vy", .bits = 32, .off_bits = 96, .cold = false },
        .{ .name = "fsm_state", .bits = 4, .off_bits = 128, .cold = false },
        .{ .name = "timer", .bits = 4, .off_bits = 132, .cold = false },
        .{ .name = "hp", .bits = 2, .off_bits = 136, .cold = false },
        .{ .name = "flash", .bits = 1, .off_bits = 138, .cold = false },
        .{ .name = "bio", .bits = 3, .off_bits = 0, .cold = true },
    } },
    .{ .name = "Turret", .row_bytes = 17, .cold_bytes = 0, .hot_bytes = 16, .fields = &[_]FieldLayout{
        .{ .name = "y", .bits = 32, .off_bits = 0, .cold = false },
        .{ .name = "vy", .bits = 32, .off_bits = 32, .cold = false },
        .{ .name = "x", .bits = 32, .off_bits = 64, .cold = false },
        .{ .name = "cool", .bits = 4, .off_bits = 96, .cold = false },
        .{ .name = "vx", .bits = 32, .off_bits = 100, .cold = false },
        .{ .name = "flash", .bits = 1, .off_bits = 132, .cold = false },
    } },
};

// ---- comptime proofs (evaluated by the Zig compiler, not the CPU) ----
comptime {
    for (ENTITIES) |e| {
        // proof 1: zero holes — dense offsets are contiguous, bit by bit
        var expect: u32 = 0;
        var dense_bits: u32 = 0;
        for (e.fields) |f| {
            if (!f.cold) {
                if (f.off_bits != expect) @compileError("SoA layout has a hole in entity " ++ e.name);
                expect += f.bits;
                dense_bits += f.bits;
            }
        }
        if (e.row_bytes != (dense_bits + 7) / 8) @compileError("row_bytes mismatch for " ++ e.name);
        // proof 2: the hot physics+render window fits one 128-bit register
        if (OPTIMIZE and e.hot_bytes > 16) @compileError("register window overflow in " ++ e.name);
    }
}

test "layout proofs" {
    // The comptime block above already proved everything; this test
    // exists so `zig test lila_opt.zig` executes the proofs.
    try std.testing.expect(ENTITIES.len >= 0);
}
