#!/usr/bin/env bash
# LILA engine build system — build-time profiles (the "CMake config.h"
# technique applied to a wasm VM).
#
# Every engine limit is a COMPTIME constant: profiles regenerate
# runtime/src/engine_config.zig, the Zig compiler specializes the whole
# memory map + pool code for that profile, and the result is exactly as
# tight as a hand-fixed build. Zero runtime cost for configurability.
#
# Usage:
#   scripts/build_engine.sh                 # default profile (v1 values)
#   scripts/build_engine.sh big             # 4MB / 2048 ent / 32 types ...
#   scripts/build_engine.sh mem_mb=8 max_ent=4096 max_types=64
#   scripts/build_engine.sh --map [profile|key=value ...]  # derived map only
#   scripts/build_engine.sh --test          # run the engine test suites
#   scripts/build_engine.sh --list          # list profiles
#
# Knobs: mem_mb max_types max_ent max_verts max_instr max_sprites max_texts
#        max_anims max_fns max_pool max_tracks max_sfx zbuffer3d(0/1)
#        gamma_blend(0/1)
#
# After building a non-default profile the committed engine_config.zig is
# RESTORED to defaults (repo hygiene) — the built artifacts keep the profile.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME="$ROOT/runtime"
CFG="$RUNTIME/src/engine_config.zig"
ZIG="${ZIG:-$HOME/.local/zig/zig}"

# ---------------- profiles (plain scalars: P_<knob>) ----------------
load_profile() {
  case "$1" in
    default)
      P_mem_mb=2; P_max_types=16; P_max_ent=512; P_max_verts=6000; P_max_instr=8192
      P_max_sprites=64; P_max_texts=32; P_max_anims=32; P_max_fns=128
      P_max_pool=1024; P_max_tracks=8; P_max_sfx=32; P_zbuffer3d=0; P_gamma_blend=0 ;;
    big)
      P_mem_mb=4; P_max_types=32; P_max_ent=2048; P_max_verts=12000; P_max_instr=12288
      P_max_sprites=128; P_max_texts=64; P_max_anims=48; P_max_fns=256
      P_max_pool=2048; P_max_tracks=8; P_max_sfx=64; P_zbuffer3d=0; P_gamma_blend=0 ;;
    huge)
      P_mem_mb=8; P_max_types=64; P_max_ent=4096; P_max_verts=24000; P_max_instr=16384
      P_max_sprites=192; P_max_texts=96; P_max_anims=64; P_max_fns=512
      P_max_pool=4096; P_max_tracks=8; P_max_sfx=96; P_zbuffer3d=0; P_gamma_blend=0 ;;
    custom)
      # defaults as the base — overrides are applied after loading
      P_mem_mb=2; P_max_types=16; P_max_ent=512; P_max_verts=6000; P_max_instr=8192
      P_max_sprites=64; P_max_texts=32; P_max_anims=32; P_max_fns=128
      P_max_pool=1024; P_max_tracks=8; P_max_sfx=32; P_zbuffer3d=0; P_gamma_blend=0 ;;
    *) echo "unknown profile '$1' (use default|big|huge or key=value)"; exit 1 ;;
  esac
}

KNOBS="mem_mb max_types max_ent max_verts max_instr max_sprites max_texts max_anims max_fns max_pool max_tracks max_sfx zbuffer3d gamma_blend"

apply_override() { # key=value with whitelist validation
  local kv="$1" key="${1%%=*}" val="${1#*=}"
  if ! echo " $KNOBS " | grep -q " $key "; then
    echo "unknown knob '$key' (knobs:$KNOBS)"; exit 1
  fi
  if ! [[ "$val" =~ ^[0-9]+$ ]]; then
    echo "knob '$key' needs a positive integer, got '$val'"; exit 1
  fi
  eval "P_$key=\$val"
}

list_profiles() {
  echo "profiles:"
  echo "  default  mem=2MB   types=16   ent=512/type    verts=6000   instr=8192   (v1 values)"
  echo "  big      mem=4MB   types=32   ent=2048/type   verts=12000  instr=12288  sprites=128 texts=64 fns=256"
  echo "  huge     mem=8MB   types=64   ent=4096/type   verts=24000  instr=16384  sprites=192 texts=96 fns=512"
  echo "custom: build_engine.sh mem_mb=4 max_types=32 max_ent=1024 max_verts=9000 ..."
}

write_config() { # $1 = profile name
  local name="$1"
  cat > "$CFG" <<EOF
//! LILA engine build profile — GENERATED by scripts/build_engine.sh (profile: $name).
//! Do not edit by hand; re-run the script to change anything here.
//! Every value is comptime: the optimizer specializes pool sizes and the
//! whole memory map for this profile. ZERO runtime cost.

pub const PROFILE_NAME: []const u8 = "$name";

/// entity types the build supports (v7; default 16 = v1 layout)
pub const MAX_TYPES: u32 = $P_max_types;
/// total flat engine memory in MB
pub const MEM_MB: u32 = $P_mem_mb;
/// entity slots per type
pub const MAX_ENT: u32 = $P_max_ent;
/// render vertex budget per frame
pub const MAX_VERTS: u32 = $P_max_verts;
/// decoded instruction capacity
pub const MAX_INSTR: u32 = $P_max_instr;
/// sprite slots
pub const MAX_SPRITES: u32 = $P_max_sprites;
/// text atoms
pub const MAX_TEXTS: u32 = $P_max_texts;
/// anim curves
pub const MAX_ANIMS: u32 = $P_max_anims;
/// functions
pub const MAX_FNS: u32 = $P_max_fns;
/// constant pool slots
pub const MAX_POOL: u32 = $P_max_pool;
/// music tracks
pub const MAX_TRACKS: u32 = $P_max_tracks;
/// sfx programs
pub const MAX_SFX: u32 = $P_max_sfx;
/// v12 3D rasterizer profile: false = painter's sort, true = per-pixel
/// Z-buffer (the runner can still override with --zbuffer / --no-zbuffer)
pub const ZBUFFER3D: bool = $([ "$P_zbuffer3d" = "1" ] && echo true || echo false);
/// v15 blending profile: false = legacy sRGB blending (v14-identical),
/// true = gamma-correct (runner overrides: --gamma / --no-gamma)
pub const GAMMA_BLEND: bool = $([ "$P_gamma_blend" = "1" ] && echo true || echo false);
EOF
}

build_all() {
  cd "$RUNTIME"
  echo "== building wasm (ReleaseSmall) =="
  "$ZIG" build-exe src/wasm.zig -target wasm32-freestanding -fno-entry \
      -rdynamic -O ReleaseSmall
  cp wasm.wasm "$ROOT/web/lila.wasm"
  echo "== building native runner (ReleaseSafe) =="
  "$ZIG" build-exe src/runner.zig -O ReleaseSafe
  echo "== map =="
  "$ZIG" run src/map_print.zig
}

# ---------------- test mode ----------------
# The v14 quality pass: the engine ships test suites — run them in one
# command instead of remembering six zig invocations.
run_tests() {
  cd "$RUNTIME"
  local failed=0
  for t in test_map test_v7 test_v11 test_v12 test_loader test_raster lila_opt; do
    echo "== $t =="
    "$ZIG" test src/$t.zig || failed=1
  done
  if [[ $failed -ne 0 ]]; then
    echo "TESTS FAILED"; exit 1
  fi
  echo "all engine tests passed"
}

# ---------------- arg parsing ----------------
if [[ "${1:-}" == "--test" ]]; then
  run_tests
  exit 0
fi

PROFILE="default"
OVERRIDES=()
PRINT_MAP_ONLY=0

if [[ $# -eq 0 ]]; then
  PROFILE="default"
elif [[ "$1" == "--list" ]]; then
  list_profiles; exit 0
elif [[ "$1" == "--map" ]]; then
  PRINT_MAP_ONLY=1; shift
  for a in "$@"; do
    if [[ "$a" == *=* ]]; then OVERRIDES+=("$a"); else PROFILE="$a"; fi
  done
  if [[ ${#OVERRIDES[@]} -gt 0 && "$PROFILE" == "default" ]]; then PROFILE="custom"; fi
else
  for a in "$@"; do
    if [[ "$a" == *=* ]]; then
      OVERRIDES+=("$a")
    else
      PROFILE="$a"
    fi
  done
  if [[ ${#OVERRIDES[@]} -gt 0 && "$PROFILE" != "custom" ]]; then
    # explicit profile + overrides = customized variant of that profile
    :
  fi
  if [[ ${#OVERRIDES[@]} -gt 0 && "$PROFILE" == "default" ]]; then PROFILE="custom"; fi
fi

load_profile "$PROFILE"
for kv in "${OVERRIDES[@]:-}"; do
  [[ -z "$kv" ]] && continue
  apply_override "$kv"
done

# backup the committed default config, restore on exit (repo hygiene)
cp "$CFG" "$CFG.default.bak"
trap 'cp "$CFG.default.bak" "$CFG"; rm -f "$CFG.default.bak"' EXIT

write_config "$PROFILE"

if [[ $PRINT_MAP_ONLY -eq 1 ]]; then
  cd "$RUNTIME" && "$ZIG" run src/map_print.zig
else
  build_all
  echo ""
  echo "built profile '$PROFILE' -> web/lila.wasm + runtime/runner"
  echo "(src/engine_config.zig restored to defaults)"
fi
